version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tiny-url"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uvxuk05y5c2s"
s3_prefix = "tiny-url"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
